# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d6106bb04b71132cbc223eaf0051d899d6a0fcf9fc6e2a1afad77ace4d0154b79734cc6a292f5c030cf0151138488647721dec40f57462ccffe2fac066cd5d4

test:
  secret_key_base: f534e4cdaa2687642c0962c8713b1e92f03cd9e3c88603b7dc46705d316d59e0b770805186a0e7c5ce85a49ca4f60ef5b1919f350512ac797a48a6b918f46a2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
